child = readtable('/Users/monaminishio/Desktop/HOME010/202402_paper/Codes/Figure2/child_mean.csv');
adult = readtable('/Users/monaminishio/Desktop/HOME010/202402_paper/Codes/Figure2/adult_mean.csv');

[rho,pchild] = partialcorr([child.Hurst, child.PVALB, child.sa]);
rho = array2table(pchild, ...
    'VariableNames',{'Hurst','PVALB','SA'},...
    'RowNames',{'Hurst','PVALB','SA'});
disp(rho)
[rho,padult] = partialcorr([adult.Hurst, adult.PVALB, adult.sa]);
rho = array2table(padult, ...
    'VariableNames',{'Hurst','PVALB','SA'},...
    'RowNames',{'Hurst','PVALB','SA'});
disp(rho)