```{r setup, include=FALSE}
#BiocManager::install("clusterProfiler")
#BiocManager::install("org.Hs.eg.db")

# Load required libraries
library(org.Hs.eg.db)
library(clusterProfiler)

stronger <- read.csv('stronger.csv')
rna_data <- data.frame(GeneID = stronger$ensembl_gene_id)
```

```{r setup, include=FALSE}
# Function to perform GO enrichment analysis and retrieve enriched biological processes
get_enriched_processes <- function(gene_ids) {
  # Map gene IDs to GO terms
  go_terms <- enrichGO(gene = gene_ids,
                       OrgDb = org.Hs.eg.db,
                       keyType = "ENSEMBL",
                       ont = "BP",  # Biological Process ontology
                       pAdjustMethod = "BH",
                       pvalueCutoff = 0.05,
                       qvalueCutoff = 0.05)
  # Retrieve enriched biological processes
  enriched_processes <- go_terms$Description
  if(length(enriched_processes) < 50) {
    enriched_processes <- c(enriched_processes, rep(NA, 50 - length(enriched_processes)))
  }
  return(enriched_processes)
}
# List of biological processes regulated by each RNA
regulated_processes <- lapply(rna_data$GeneID, get_enriched_processes)
# Combine the results into a data frame
result_df <- data.frame(regulated_processes)
colnames(result_df) <- rna_data$GeneID
write.csv(result_df, 'stronger_go.csv')
```