---
title: "Piper Functional Maturity"
author: "Cassidy McDermott"
date: "8/19/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("WinVector/WVPlots")
library(WVPlots)
library(clue)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(cowplot)
theme_set(theme_cowplot())
library(corrplot)
library(visreg)
library(ggcorrplot)
library(ggseg3d)
library(ggseg)
library(ggsegSchaefer)
library(ggsegYeo2011)
library(psych)
library(nlme)
library(mgcv)
library(gratia)

source("/Users/monaminishio/Desktop/HOME8/SurfaceArea/scripts/R/rotate.parcellation.R")
source("/Users/monaminishio/Desktop/HOME8/SurfaceArea/scripts/R/perm.sphere.p.R")

load(file="/Users/monaminishio/Desktop/HOME8/SurfaceArea/scripts/R/schaefer7_400_3d.rda")
lh_label <- schaefer7_400_3d$ggseg_3d[[1]]['region'][2:201,1:1]
rh_label <- schaefer7_400_3d$ggseg_3d[[2]]['region'][2:201,1:1]

age_H <- read.csv("/Users/monaminishio/Desktop/HOME8/Functional/derivative/hurst_exponent/hurst_age_sorted_sensitivity.csv") 
H  <- read.csv('/Users/monaminishio/Desktop/HOME8/SurfaceArea/scripts/pvalues/concat_original.csv')
# Figure1G
colfunc <- colorRampPalette(c("yellow","purple"))(400)
postscript('figures/Figure1G_sensitivity.eps') 
for (n in 1:400){
  col <- colnames(age_H)[n+1]
  model <- gam(scale(age_H[[col]]) ~ s(age_scan, k=3) + male + t1_rating_avg, data = age_H)
  if (n==400){
    plot(model, se=FALSE, residuals=FALSE, shade=FALSE, col=colfunc[n], ylim=c(-1,1), ylab='Hurst Exponent (z-scored)', xlim=c(4,9), xlab='Age')}
  else {
    plot(model, se=FALSE, residuals=FALSE, shade=FALSE, col=colfunc[n], ylim=c(-1,1), ylab='',yaxt="n" ,  xlim=c(4,9),xlab='',xaxt="n" )
  par(new=T)}
}
dev.off()
postscript('figures/Figure1H_sensitivity.eps') 
ggMarginal(ggplot(age_H, aes(age_scan, age_scan), ylim=c(-1,1)) + geom_point(), type="histogram")
dev.off()
#ScatterHist(age_H, "age_scan", col, title='age')

# Figure1H
derivatives <- data.frame(derv=1:400)
for (n in 1:400){
  col <- colnames(age_H)[n+1]
  model <- gam(scale(age_H[[col]]) ~ s(age_scan, k=3) + male + t1_rating_avg, data = age_H)
  derv <- derivatives(model, interval = "simultaneous", unconditional = F)
  derv <- derv %>% #add "sig" column (TRUE/FALSE) to derv
    mutate(sig = !(0 > lower & 0 < upper)) #derivative is sig if the lower CI is not < 0 while the upper CI is > 0 (i.e., when the CI does not include 0)
  derv$sig_deriv = derv$derivative*derv$sig #add "sig_deriv derivatives column where non-significant derivatives are set to 0
  decreasing.range <- derv$data[derv$derivative > 0] 
  if(length(decreasing.range) > 0)
    #res <- lm(derv$derivative[derv$derivative > 0]~derv$data[derv$derivative > 0])
    #derivatives$derv[n] <- res$coefficients[[2]]
    derivatives$derv[n] <- mean(derv$derivative[derv$derivative > 0])
  if(length(decreasing.range) == 0)
    derivatives$derv[n] <- NA
}
colfunc <- colorRampPalette(c("yellow","purple"))(400)
postscript('figures/Figure1H_sensitivity.eps') 
plot(sort(H[['HArank']]),derivatives[['derv']],
   xlab="S-Aaxis", ylab="Hurst Exponent decrease onset", pch=19, col=colfunc[sort(H[['HArank']])])
lmresult <- lm(derivatives[['derv']]~sort(H[['HArank']]))
preds <- predict(lmresult, newdata=data.frame(sort(H[['HArank']])), interval="confidence", level = 0.95)
abline(lmresult, col="black")
polygon(c(rev(sort(H[['HArank']])), sort(H[['HArank']])), c(rev(preds[ ,3]), preds[ ,2]), col = 'grey80', border = NA)
print(summary(lmresult))
dev.off()
#write_csv(derivatives, '/Users/monaminishio/Desktop/HOME8/SurfaceArea/scripts/pvalues/H_gam_derivatives.csv')
```

```{r setup, include=FALSE}
# Figure1I:ver3
colfunc <- colorRampPalette(c("yellow","purple"))(400)
postscript(paste('figures/Figure1I_sensitivity', n, '.eps'))
for (n in c(0,133,266)){
  col <- colnames(age_H)[(2+n):(134+n)]
  model <- gam(scale(rowMeans(age_H[col])) ~ s(age_scan, k=3) + male + t1_rating_avg, data = age_H)
  plot(model, se=TRUE, residuals=FALSE, shade=TRUE, shade.col=colfunc[n+1], shade.alpha=0.1,col=colfunc[n+1], xlim=c(4,9), ylab='Hurst Exponent (z-scored)', xlab='Age',ylim=c(-1,1)) # 
  par(new=T)
  derv <- derivatives(model, interval = "simultaneous", unconditional = F)
  derv <- derv %>% #add "sig" column (TRUE/FALSE) to derv
    mutate(sig = !(0 > lower & 0 < upper)) #derivative is sig if the lower CI is not < 0 while the upper CI is > 0 (i.e., when the CI does not include 0)
  derv$sig_deriv = derv$derivative*derv$sig #add "sig_deriv derivatives column where non-significant derivatives are set to 0
  decreasing.range <- derv$data[derv$derivative < 0] 
  if(length(decreasing.range) > 0)
    derivatives$derv[n] <- min(decreasing.range) #find youngest age with a significant negative derivative
  plot(c(min(decreasing.range),min(decreasing.range)), c(-1,1), type="l", xlim=c(4,9), ylab='Hurst Exponent (z-scored)', xlab='Age',ylim=c(-1,1),col=colfunc[n+1])
  par(new=T)
}
dev.off()
```