```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("WinVector/WVPlots")
library(WVPlots)
library(clue)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(cowplot)
theme_set(theme_cowplot())
library(corrplot)
library(visreg)
library(ggcorrplot)
library(ggseg3d)
library(ggseg)
library(ggsegSchaefer)
library(ggsegYeo2011)
library(psych)
library(nlme)
library(mgcv)
library(gratia)

load(file="../modules/schaefer7_400_3d.rda")
lh_label <- schaefer7_400_3d$ggseg_3d[[1]]['region'][2:201,1:1]
rh_label <- schaefer7_400_3d$ggseg_3d[[2]]['region'][2:201,1:1]
label <- rbind(lh_label, rh_label)

age_H <- read.csv("../derivatives/childhood/hurst.csv") 
age_H_sorted <- read.csv("../derivatives/childhood/hurst_sorted.csv") 
concat <- read.csv('../derivatives/childhood/original.csv')
```

```{r setup, include=FALSE}
schaefer_H <- data.frame(age=1:400)
pvalue <- data.frame(age=1:400)
for (n in 1:400){
  col <- colnames(age_H)[n]
  gam.model <- gam(scale(age_H[[col]]) ~ s(age_scan, k=3) + male + t1_rating_avg, data = age_H)
  gam.nullmodel <- gam(scale(age_H[[col]]) ~ male + t1_rating_avg, data = age_H)
  derv <- derivatives(gam.model, interval = "simultaneous", unconditional = F)
  pvalue$age[n] <- anova.gam(gam.nullmodel, gam.model, test='Chisq')$`Pr(>Chi)`[2]
  ### effect size
  sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
  sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
  partialRsq <- (sse.nullmodel - sse.model)/sse.nullmodel
  ### effect direction
  mean.derivative <- mean(derv$derivative)
  if(mean.derivative < 0){ #if the average derivative is less than 0, make the effect size estimate negative
    partialRsq <- partialRsq*-1}
  schaefer_H$age[n] <- partialRsq
  }
```

```{r setup, include=FALSE}
correctedpvalue <- data.frame(age=1:400)
correctedpvalue$age <- p.adjust(pvalue$age, method=c("fdr")) < 0.05
pvalue$age <- pvalue$age < 0.05
schaefer_H_extractp <- schaefer_H
schaefer_H_extractp[pvalue==FALSE] <- NA
schaefer_H_extractp <- cbind(schaefer_H_extractp, label)
schaefer_H_extractpadj <- schaefer_H
schaefer_H_extractpadj[correctedpvalue==FALSE] <- NA
schaefer_H_extractpadj <- cbind(schaefer_H_extractpadj, label)
```

```{r setup, include=FALSE}
# Figure3A
ggseg(schaefer_H_extractp, atlas = schaefer7_400, mapping = aes(fill = age), 
      position = "stacked") +
  scale_fill_gradientn(colours=c("blue", 'white', "red"), name = bquote(age_effect), values = scales::rescale(c(-0.5, -0.05, 0, 0.05, 0.5)), limit=c(-0.3, 0.3)) + theme_brain(text.size=16)
ggsave(filename ='../figures/Fig3A.eps', device = "pdf", dpi = 500) #, width = .5 , height = .5
```

```{r setup, include=FALSE}
# Figure3B
colfunc <- colorRampPalette(c("yellow","purple"))(400)
postscript('../figures/Fig3B.eps') 
for (n in 1:400){
  col <- colnames(age_H_sorted)[n]
  model <- gam(scale(age_H_sorted[[col]]) ~ s(age_scan, k=3) + male + t1_rating_avg, data = age_H_sorted)
  if (n==400){
    plot(model, se=FALSE, residuals=FALSE, shade=FALSE, col=colfunc[n], ylim=c(-1,1), ylab='Hurst Exponent (z-scored)', xlim=c(4,11), xlab='Age')}
  else {
    plot(model, se=FALSE, residuals=FALSE, shade=FALSE, col=colfunc[n], ylim=c(-1,1), ylab='',yaxt="n" ,  xlim=c(4,11),xlab='',xaxt="n" )
  par(new=T)}
}
dev.off()
postscript('../figures/Fig3B_age.eps') 
ggMarginal(ggplot(age_H_sorted, aes(age_scan, age_scan), ylim=c(-1,1)) + geom_point(), type="histogram")
dev.off()
```

```{r setup, include=FALSE}
# Figure3C
derivatives <- data.frame(derv=1:400)
for (n in 1:400){
  col <- colnames(age_H_sorted)[n]
  model <- gam(scale(age_H_sorted[[col]]) ~ s(age_scan, k=3) + male + t1_rating_avg, data = age_H_sorted)
  derv <- derivatives(model, interval = "simultaneous", unconditional = F)
  derv <- derv %>% #add "sig" column (TRUE/FALSE) to derv
    mutate(sig = !(0 > lower & 0 < upper)) #derivative is sig if the lower CI is not < 0 while the upper CI is > 0 (i.e., when the CI does not include 0)
  derv$sig_deriv = derv$derivative*derv$sig #add "sig_deriv derivatives column where non-significant derivatives are set to 0
  decreasing.range <- derv$data[derv$derivative > 0] 
  if(length(decreasing.range) > 0)
    derivatives$derv[n] <- mean(derv$derivative[derv$derivative > 0])
  if(length(decreasing.range) == 0)
    derivatives$derv[n] <- NA
}
colfunc <- colorRampPalette(c("yellow","purple"))(400)
postscript('../figures/Fig3C.eps') 
plot(sort(concat[['SArank']]),derivatives[['derv']],
   xlab="S-Aaxis", ylab="Hurst Exponent decrease onset", pch=19, col=colfunc[sort(concat[['SArank']])])
lmresult <- lm(derivatives[['derv']]~sort(concat[['SArank']]))
preds <- predict(lmresult, newdata=data.frame(sort(concat[['SArank']])), interval="confidence", level = 0.95)
abline(lmresult, col="black")
polygon(c(rev(sort(concat[['SArank']])), sort(concat[['SArank']])), c(rev(preds[ ,3]), preds[ ,2]), col = 'grey80', border = NA)
print(summary(lmresult))
dev.off()
write_csv(derivatives, '../derivatives/childhood/H_gam_derivatives.csv')
```

```{r setup, include=FALSE}
# Figure3D
colfunc <- colorRampPalette(c("yellow","purple"))(400)
postscript('../figures/Fig3D.eps')
for (n in c(1,134,267)){
  col <- colnames(age_H_sorted)[(n):(133+n)]
  model <- gam(scale(rowMeans(age_H_sorted[col])) ~ s(age_scan, k=3) + male + t1_rating_avg, data = age_H_sorted)
  plot(model, se=TRUE, residuals=TRUE, shade=TRUE, shade.col=colfunc[n], shade.alpha=0.1, ylim=c(-2,2),col=colfunc[n], xlim=c(4,11), ylab='Hurst Exponent (z-scored)', xlab='Age') # ylim=c(-2,2),
  par(new=T)
  derv <- derivatives(model, interval = "simultaneous", unconditional = F)
  derv <- derv %>% #add "sig" column (TRUE/FALSE) to derv
    mutate(sig = !(0 > lower & 0 < upper)) #derivative is sig if the lower CI is not < 0 while the upper CI is > 0 (i.e., when the CI does not include 0)
  derv$sig_deriv = derv$derivative*derv$sig #add "sig_deriv derivatives column where non-significant derivatives are set to 0
  decreasing.range <- derv$data[derv$derivative < 0] 
  if(length(decreasing.range) > 0)
    derivatives$derv[n] <- min(decreasing.range) #find youngest age with a significant negative derivative
  plot(c(min(decreasing.range),min(decreasing.range)), c(-2,2), type="l", xlim=c(4,11), ylab='Hurst Exponent (z-scored)', xlab='Age',ylim=c(-1,1),col=colfunc[n])
  par(new=T)
}
dev.off()
```

```{r setup, include=FALSE}
# Figure3E
for (n in c(1,134,267)){
  postscript(paste('../figures/Fig3E', n, '.eps'))
  col <- colnames(age_H)[(1+n):(133+n)]
  model <- gam(scale(rowMeans(age_H_sorted[col])) ~ s(age_scan, k=3) + male + t1_rating_avg, data = age_H_sorted)
  plot(model, se=TRUE, residuals=TRUE, shade=TRUE, shade.col=colfunc[n], shade.alpha=0.1, ylim=c(-2,2),col=colfunc[n], xlim=c(4,11), ylab='Hurst Exponent (z-scored)', xlab='Age') 
  par(new=T)
  derv <- derivatives(model, interval = "simultaneous", unconditional = F)
  derv <- derv %>% #add "sig" column (TRUE/FALSE) to derv
    mutate(sig = !(0 > lower & 0 < upper)) #derivative is sig if the lower CI is not < 0 while the upper CI is > 0 (i.e., when the CI does not include 0)
  derv$sig_deriv = derv$derivative*derv$sig #add "sig_deriv derivatives column where non-significant derivatives are set to 0
  decreasing.range <- derv$data[derv$derivative < 0] 
  if(length(decreasing.range) > 0)
    derivatives$derv[n] <- min(decreasing.range) #find youngest age with a significant negative derivative
  plot(c(min(decreasing.range),min(decreasing.range)), c(-2,2), type="l", xlim=c(4,11), ylab='Hurst Exponent (z-scored)', xlab='Age', ylim=c(-1,1),col=colfunc[n]) 
  dev.off()
}
```