```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("WinVector/WVPlots")
library(WVPlots)
library(clue)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(cowplot)
library(car)
theme_set(theme_cowplot())
library(corrplot)
library(visreg)
library(ggcorrplot)
library(ggseg3d)
library(ggseg)
library(ggsegSchaefer)
library(ggsegYeo2011)
library(psych)
library(nlme)
library(mgcv)
library(gratia)

load(file="../../Dataset/childhood/atlas/schaefer17_400_3d.RData")
lh_label <- schaefer17_400_3d$ggseg_3d[[1]]['region'][2:201,1:1]
rh_label <- schaefer17_400_3d$ggseg_3d[[2]]['region'][2:201,1:1]
label <- rbind(lh_label, rh_label)
age_H <- read.csv("../../Derivatives/childhood/hurst_motion_1mm.csv")   
age_H_sorted <- read.csv("../../Derivatives/childhood/hurst_sorted_motion_1mm.csv")
concat <- read.csv('../../Derivatives/childhood/original_motion_1mm.csv')
brod <- read.csv('../../Derivatives/childhood/hurst_brodmann.csv')
brainmap <- read.csv("../../Derivatives/childhood/brainmap.csv") 
brainmap <- cbind(brainmap, label)
age_H <- age_H[age_H$sub!='CBPD0015',]
age_H <- age_H[age_H$sub!='CBPD0247',]
age_H_sorted <- age_H_sorted[age_H_sorted$sub!='CBPD0015',]
age_H_sorted <- age_H_sorted[age_H_sorted$sub!='CBPD0247',]
k=3
```

```{r setup, include=FALSE}
# Figure3A
colfunc <- colorRampPalette(c("yellow","purple"))(400)
n <-1
col <- colnames(age_H_sorted)[(n):(133+n)]
allcol <- age_H_sorted[col[1]]
colnames(allcol) <- 'age'
for (x in col){
  colconcat <- age_H_sorted[x]
  colnames(colconcat) <- 'age'
  allcol <- rbind(allcol, colconcat)}
allages <- age_H_sorted['age_scan']
for (x in col){
  allages <- rbind(allages, age_H_sorted['age_scan'])}
allsex <- age_H_sorted['male']
for (x in col){
  allsex <- rbind(allsex, age_H_sorted['male'])}
allmotion <- age_H_sorted['meanFD']
for (x in col){
  allmotion <- rbind(allmotion, age_H_sorted['meanFD'])}
allcol <- cbind(allcol, allages, allsex, allmotion)
model <- gam(allcol[['age']] ~ s(age_scan, k=k) + male + meanFD, data = allcol)
pred <- predict(model, se.fit=T)
derv <- derivatives(model, interval = "simultaneous", unconditional = F)
increasing.range <- derv[['age_scan']][derv[['.lower_ci']] > 0]
print(max(increasing.range))
allcol$prediction <- pred$fit
allcol$ymin <- pred$fit-1.96*pred$se.fit
allcol$ymax <- pred$fit+1.96*pred$se.fit
p <- ggplot(data = allcol, mapping = aes(x = age_scan, y = prediction)) +
geom_smooth(method="gam", formula= y~s(x, k=k), se=TRUE, alpha=1) + ylim(1.0,1.2)
ggsave('Fig3B_1mm_noregress_267.eps', plot=p, width=6, height=4, units='in', dpi=300)#, device="eps")

postscript('Fig3B_1mm_noregress_134.eps')
n <- 134
col <- colnames(age_H_sorted)[(n):(133+n)]
allcol <- age_H_sorted[col[1]]
colnames(allcol) <- 'age'
for (x in col){
  colconcat <- age_H_sorted[x]
  colnames(colconcat) <- 'age'
  allcol <- rbind(allcol, colconcat)}
allages <- age_H_sorted['age_scan']
for (x in col){
  allages <- rbind(allages, age_H_sorted['age_scan'])}
allsex <- age_H_sorted['male']
for (x in col){
  allsex <- rbind(allsex, age_H_sorted['male'])}
allmotion <- age_H_sorted['meanFD']
for (x in col){
  allmotion <- rbind(allmotion, age_H_sorted['meanFD'])}
allcol <- cbind(allcol, allages, allsex, allmotion)
model <- gam(allcol[['age']] ~ s(age_scan, k=k) + male + meanFD, data = allcol)
pred <- predict(model, se.fit=T)
ggplot(data = allcol, mapping = aes(x = age_scan, y = age)) +
geom_smooth(method="gam", formula= y~s(x, k=k)) + ylim(1.1,1.2)
dev.off()

postscript('Fig3B_1mm_noregress_267.eps')
n <- 267
col <- colnames(age_H_sorted)[(n):(133+n)]
allcol <- age_H_sorted[col[1]]
colnames(allcol) <- 'age'
for (x in col){
  colconcat <- age_H_sorted[x]
  colnames(colconcat) <- 'age'
  allcol <- rbind(allcol, colconcat)}
allages <- age_H_sorted['age_scan']
for (x in col){
  allages <- rbind(allages, age_H_sorted['age_scan'])}
allsex <- age_H_sorted['male']
for (x in col){
  allsex <- rbind(allsex, age_H_sorted['male'])}
allmotion <- age_H_sorted['meanFD']
for (x in col){
  allmotion <- rbind(allmotion, age_H_sorted['meanFD'])}
allcol <- cbind(allcol, allages, allsex, allmotion)
model <- gam(allcol[['age']] ~ s(age_scan, k=k) + male + meanFD, data = allcol)
pred <- predict(model, se.fit=T)
ggplot(data = allcol, mapping = aes(x = age_scan, y = age)) +
geom_smooth(method="gam", formula= y~s(x, k=k)) + ylim(1.1,1.2)
dev.off()
```

```{r setup, include=FALSE}
schaefer_H <- data.frame(age=1:400)
pvalue <- data.frame(age=1:400)
increase <- data.frame(age=1:400)
increase_2 <- data.frame(age=1:400)
for (n in 1:400){
  col <- colnames(age_H)[n]
  gam.model <- gam(age_H[[col]] ~ s(age_scan, k=k) + male + meanFD, data = age_H)
  gam.nullmodel <- gam(age_H[[col]] ~ male + meanFD, data = age_H)
  derv <- derivatives(gam.model, interval = "simultaneous", unconditional = F)
  pvalue$age[n] <- anova.gam(gam.nullmodel, gam.model, test='Chisq')$`Pr(>Chi)`[2]
  ### effect size
  sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
  sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
  partialRsq <- (sse.nullmodel - sse.model)/sse.nullmodel
  ### effect direction
  mean.derivative <- mean(derv[['.derivative']])
  if(mean.derivative < 0){ #if the average derivative is less than 0, make the effect size estimate negative
    partialRsq <- partialRsq*-1}
  schaefer_H$age[n] <- partialRsq
  increasing.range <- derv[['age_scan']][derv[['.lower_ci']] > 0]
  increase$age[n] <- max(increasing.range)
  increasing.range <- derv[['age_scan']][derv[['.derivative']] > 0]
  increase_2$age[n] <- max(increasing.range)
}
```

```{r setup, include=FALSE}
correctedpvalue <- data.frame(age=1:400)
correctedpvalue$age <- p.adjust(pvalue$age, method=c("fdr")) < 0.05
pvalue$age <- pvalue$age < 0.05
schaefer_H_extractp <- schaefer_H
schaefer_H_extractp[pvalue==FALSE] <- NA
schaefer_H_extractp <- cbind(schaefer_H_extractp, label)
schaefer_H_extractpadj <- schaefer_H
schaefer_H_extractpadj[correctedpvalue==FALSE] <- NA
schaefer_H_extractpadj <- cbind(schaefer_H_extractpadj, label)
```

```{r setup, include=FALSE}
# Figure 3C
schaefer_H_extractp$plateau <- increase$age
schaefer_H_extractp$sa <- brainmap$X3
schaefer_nonlinear <- schaefer_H_extractp[schaefer_H_extractp$plateau<10, ]
schaefer_nonlinear <- schaefer_nonlinear[schaefer_nonlinear$plateau>0, ]
schaefer_linear <- schaefer_H_extractp[schaefer_H_extractp$plateau>10, ]
print(median(schaefer_nonlinear$sa))
print(median(schaefer_linear$sa))
ggseg(schaefer_nonlinear, atlas = schaefer17_400, mapping = aes(fill = age),
      position = "stacked") +
  scale_fill_gradientn(colours=c("blue", 'white', "red"), name = bquote(age_effect), values = scales::rescale(c(-0.5, -0.05, 0, 0.05, 0.5)), limit=c(-0.1, 0.1)) + theme_brain(text.size=16)
ggsave(filename ='Fig3C_nonlinear.eps', device = "pdf", dpi = 500)
ggseg(schaefer_linear, atlas = schaefer17_400, mapping = aes(fill = age),
      position = "stacked") +
  scale_fill_gradientn(colours=c("blue", 'white', "red"), name = bquote(age_effect), values = scales::rescale(c(-0.5, -0.05, 0, 0.05, 0.5)), limit=c(-0.1, 0.1)) + theme_brain(text.size=16)
ggsave(filename ='Fig3C_linear.eps', device = "pdf", dpi = 500) #, width = .5 , height = .5
```

```{r setup, include=FALSE}
# Figure 3D
schaefer_H[['SArank']] <- concat[['SArank']]
model <- gam(schaefer_H[['age']] ~ s(SArank), data = schaefer_H)
pred <- predict(model, se.fit=T)
ggplot(data = schaefer_H, mapping = aes(x = SArank, y = age)) +
  geom_point(aes(color = schaefer_H[['SArank']])) + ylim(0, 0.12) +  xlim(0, 400) +
  geom_ribbon(aes(ymin=pred$fit-1.96*pred$se.fit,
                   ymax=pred$fit+1.96*pred$se.fit), alpha = 1, fill = 'gray') +
  geom_smooth(method="gam", formula= y~s(x, k=k)) + scale_color_gradient(low='yellow', high='purple') +
  geom_line(size=.3, alpha = .8)  + theme(legend.position='none')
ggsave(file='Figure3D_nocorrection.eps', width=6, height=4, dpi=300)
print(summary(model))
```

```{r setup, include=FALSE}
# Figure 3B YEO7network
colfunc <- c('darkmagenta', 'blue', 'darkgreen','magenta3','palegreen1',  'orange','red')
postscript('Fig3B_1mm_7network.eps')
schaefer_H <- data.frame(age=1:7)
pvalue <- data.frame(age=1:7)
threslist <- c(1,25,60,86,109,121,149,201,224,259,285,313,325,358,400)
n <- 2
col <- c(colnames(age_H)[threslist[n]:threslist[n+1]], colnames(age_H)[threslist[n+7]:threslist[n+8]])
allcol <- age_H[col[1]]
colnames(allcol) <- 'age'
for (x in col){
  colconcat <- age_H[x]
  colnames(colconcat) <- 'age'
  allcol <- rbind(allcol, colconcat)}
allages <- age_H['age_scan']
for (x in col){
  allages <- rbind(allages, age_H['age_scan'])}
allsex <- age_H['male']
for (x in col){
  allsex <- rbind(allsex, age_H['male'])}
allmotion <- age_H['meanFD']
for (x in col){
  allmotion <- rbind(allmotion, age_H['meanFD'])}
allcol <- cbind(allcol, allages, allsex, allmotion)
model <- gam(allcol[['age']] ~ s(age_scan, k=k) + male + meanFD, data = allcol)
gam.model <- gam(allcol[['age']] ~ s(age_scan, k=k) + male + meanFD, data = allcol)
gam.nullmodel <- gam(allcol[['age']] ~ male + meanFD, data = allcol)
### effect size
sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
partialRsq <- (sse.nullmodel - sse.model)/sse.nullmodel
derv <- derivatives(gam.model, interval = "simultaneous", unconditional = F)
mean.derivative <- mean(derv[['.derivative']])
if(mean.derivative < 0){ #if the average derivative is less than 0, make the effect size estimate negative
  partialRsq <- partialRsq*-1}
schaefer_H$age[n] <- partialRsq
pvalue$age[n] <- anova.gam(gam.nullmodel, gam.model, test='Chisq')$`Pr(>Chi)`[2]
increasing.range <- derv[['age_scan']][derv[['.lower_ci']] > 0]
pred <- predict(model, se.fit=T)
allcol$prediction <- pred$fit
p <- ggplot(data = allcol, mapping = aes(x = age_scan, y = prediction)) +
geom_smooth(method="gam", formula= y~s(x, k=k), se=TRUE, alpha=1) + ylim(0.95,1.25) + xlim(4,11)
ggsave(paste('Fig3B_', n, '.eps'), plot=p, width=6, height=4, units='in', dpi=300)
dev.off()
```