```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#devtools::install_github("WinVector/WVPlots")
library(WVPlots)
library(clue)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(cowplot)
theme_set(theme_cowplot())
library(corrplot)
library(visreg)
library(ggcorrplot)
library(ggseg3d)
library(ggseg)
library(ggsegSchaefer)
library(ggsegYeo2011)
library(psych)
library(nlme)
library(mgcv)
library(gratia)

age_H_original <- read.csv("../../Derivatives/mouse/AD1.csv")
age_H_selected <- read.csv("../../Derivatives/mouse/AD1_selected.csv")
sa <- read.csv("../../Derivatives/mouse/sa.csv")
k=3
```

```{r setup, include=FALSE}
# Figure 4D
age_H_selected <- age_H_selected[age_H_selected$age < 8, ]
colfunc <- colorRampPalette(c("yellow","purple"))(3)
pvalue <- data.frame(age=1:3)
schaefer_H <- data.frame(age=1:3)
i <- 1
index <- which(sa$sa_bin %in% i)
col <- colnames(age_H_selected)[index]
allcol <- age_H_selected[col[1]]
colnames(allcol) <- 'ageeffect'
for (x in col){
  colconcat <- age_H_selected[x]
  colnames(colconcat) <- 'ageeffect'
  allcol <- rbind(allcol, colconcat)}
allages <- age_H_selected['age']
for (x in col){
  allages <- rbind(allages, age_H_selected['age'])}
allsex <- age_H_selected['gender']
for (x in col){
  allsex <- rbind(allsex, age_H_selected['gender'])}
allcol <- cbind(allcol, allages, allsex)
model <- gam(allcol[['ageeffect']] ~ s(age, k=k) + gender, data = allcol)
pred <- predict(model, se.fit=T)
gam.model <- gam(allcol[['ageeffect']] ~ s(age, k=k) + gender, data = allcol)
gam.nullmodel <- gam(allcol[['ageeffect']] ~ gender, data = allcol)
pvalue$age[i] <- anova.gam(gam.nullmodel, gam.model, test='Chisq')$`Pr(>Chi)`[2]
sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
partialRsq <- (sse.nullmodel - sse.model)/sse.nullmodel
schaefer_H$age[i] <- partialRsq
derv <- derivatives(model, interval = "simultaneous", unconditional = F)
increasing.range <- derv[['age']][derv[['.lower_ci']] > 0] 
print(max(increasing.range))
allcol$prediction <- pred$fit
p <- ggplot(data = allcol, mapping = aes(x = age, y = prediction)) +
geom_smooth(method="gam", formula= y~s(x, k=k), se=TRUE, alpha=1, level=0.9999) + ylim(0.85,0.95)
ggsave(paste('Fig4D_1mm_noregress_', i,'.eps'), plot=p, width=6, height=4, units='in', dpi=300)
```

```{r setup, include=FALSE}
age_H_selected <- age_H_selected[age_H_selected$age < 8, ]
schaefer_H <- data.frame(age=1:34)
pvalue <- data.frame(age=1:34)
for (n in 1:34){
  col <- colnames(age_H_selected)[n]
  gam.model <- gam(scale(age_H_selected[[col]]) ~ s(age, k=k) + gender, data = age_H_selected)
  gam.nullmodel <- gam(scale(age_H_selected[[col]]) ~ gender, data = age_H_selected)
  pvalue$age[n] <- anova.gam(gam.nullmodel, gam.model, test='Chisq')$`Pr(>Chi)`[2]
  ### effect size
  sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
  sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
  partialRsq <- (sse.nullmodel - sse.model)/sse.nullmodel
  schaefer_H$age[n] <- partialRsq
  }
```

```{r setup, include=FALSE}
schaefer_H['sa'] <- sa$sa
model <- gam(schaefer_H[['age']] ~ s(sa, k=k), data = schaefer_H)
pred <- predict(model, se.fit=T)
ggplot(data = schaefer_H, mapping = aes(x = sa, y = age)) +
  geom_point(aes(color = schaefer_H[['sa']])) + #+ ylim(-0.05, 0.1) +
  geom_ribbon(aes(ymin=pred$fit-1.96*pred$se.fit,
                   ymax=pred$fit+1.96*pred$se.fit), alpha = 1, fill = 'gray') +
  geom_smooth(method="gam", formula= y~s(x, k=k)) + scale_color_gradient(low='yellow', high='purple') +
  geom_line(size=.3, alpha = .8)
ggsave(file='Figure4E.eps', width=8, height=4, dpi=300)
print(summary(model))
```

