```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("WinVector/WVPlots")
library(WVPlots)
library(clue)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(cowplot)
theme_set(theme_cowplot())
library(corrplot)
library(visreg)
library(ggcorrplot)
library(ggseg3d)
library(ggseg)
library(ggsegSchaefer)
library(ggsegYeo2011)
library(psych)
library(nlme)
library(mgcv)
library(gratia)

age_H_original <- read.csv("../../Derivatives/H_age_original.csv")   
age_H <- read.csv("../../Derivatives/H_age.csv")   
age_H_mean <- read.csv("../../Derivatives/H_age_mean.csv")   
sa <- read.csv("../../Derivatives/sa.csv")   

k=3
```

```{r setup, include=FALSE}
schaefer_H <- data.frame(age=1:232)
pvalue <- data.frame(age=1:232)
for (n in 1:232){
  col <- colnames(age_H_original)[n]
  gam.model <- gam(scale(age_H_original[[col]]) ~ s(Age, k=k) + Sex, data = age_H_original)
  gam.nullmodel <- gam(scale(age_H_original[[col]]) ~ Sex, data = age_H_original)
  derv <- derivatives(gam.model, interval = "simultaneous", unconditional = F)
  pvalue$age[n] <- anova.gam(gam.nullmodel, gam.model, test='Chisq')$`Pr(>Chi)`[2]
  ### effect size
  sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
  sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
  partialRsq <- (sse.nullmodel - sse.model)/sse.nullmodel
  ### effect direction
  mean.derivative <- mean(derv$derivative)
  if(mean.derivative < 0){ #if the average derivative is less than 0, make the effect size estimate negative
    partialRsq <- partialRsq*-1}
  schaefer_H$age[n] <- partialRsq
  }
```

```{r setup, include=FALSE}
correctedpvalue <- data.frame(age=1:232)
correctedpvalue$age <- p.adjust(pvalue$age, method=c("fdr")) < 0.05
pvalue$age <- pvalue$age < 0.05
schaefer_H_extractp <- schaefer_H
schaefer_H_extractp[pvalue==FALSE] <- NA
schaefer_H_extractpadj <- schaefer_H
schaefer_H_extractpadj[correctedpvalue==FALSE] <- NA
write.csv(schaefer_H, '../../Derivatives/Figure4/ageeffect.csv')
write.csv(schaefer_H_extractp, '../../Derivatives/Figure4/nocorrected_ageeffect.csv')
write.csv(schaefer_H_extractpadj, '../../Derivatives/Figure4/corrected_ageeffect.csv')
```

```{r setup, include=FALSE}
# Figure3D
colfunc <- colorRampPalette(c("yellow","purple"))(400)
#postscript('../figures/Fig3D.eps')
col <- colnames(age_H_original)[1:232]
allcol <- age_H_original[col[1]]
colnames(allcol) <- 'age'
for (x in col){
  colconcat <- age_H_original[x]
  colnames(colconcat) <- 'age'
  allcol <- rbind(allcol, colconcat)}
allages <- age_H['Age']
for (x in col){
  allages <- rbind(allages, age_H_original['Age'])}
allsex <- age_H['Sex']
for (x in col){
  allsex <- rbind(allsex, age_H_original['Sex'])}
allcol <- cbind(allcol, allages, allsex)
model <- gam(allcol[['age']] ~ s(Age, k=k) + Sex, data = allcol)
plot(model, se=TRUE, residuals=FALSE, shade=TRUE, shade.col=colfunc[n], shade.alpha=0.1, col=colfunc[n], ylab='Hurst Exponent (z-scored)', xlab='Age') # ylim=c(-0.5,0.5),
dev.off()
print(summary(model))
```


```{r setup, include=FALSE}
schaefer_H <- data.frame(age=1:34)
pvalue <- data.frame(age=1:34)
for (n in 1:34){
  col <- colnames(age_H)[n]
  gam.model <- gam(scale(age_H[[col]]) ~ s(Age, k=k) + Sex, data = age_H)
  gam.nullmodel <- gam(scale(age_H[[col]]) ~ Sex, data = age_H)
  derv <- derivatives(gam.model, interval = "simultaneous", unconditional = F)
  pvalue$age[n] <- anova.gam(gam.nullmodel, gam.model, test='Chisq')$`Pr(>Chi)`[2]
  ### effect size
  sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
  sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
  partialRsq <- (sse.nullmodel - sse.model)/sse.nullmodel
  ### effect direction
  mean.derivative <- mean(derv$derivative)
  if(mean.derivative < 0){ #if the average derivative is less than 0, make the effect size estimate negative
    partialRsq <- partialRsq*-1}
  schaefer_H$age[n] <- partialRsq
  }
```

```{r setup, include=FALSE}
schaefer_H['sa'] <- sa
model <- gam(schaefer_H[['age']] ~ s(sa, k=k), data = schaefer_H)
pred <- predict(model, se.fit=T)
ggplot(data = schaefer_H, mapping = aes(x = sa, y = age)) +
  geom_point(aes(color = schaefer_H[['sa']])) + ylim(-0.05, 0.1) +
  geom_ribbon(aes(ymin=pred$fit-1.96*pred$se.fit,
                   ymax=pred$fit+1.96*pred$se.fit), alpha = 1, fill = 'gray') +
  geom_smooth(method="gam", formula= y~s(x, k=k)) + scale_color_gradient(low='yellow', high='purple') +
  geom_line(size=.3, alpha = .8)
ggsave(file='Figure3A4-11sa.eps', width=8, height=4, dpi=300)
print(summary(model))
```