```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("WinVector/WVPlots")
library(WVPlots)
library(clue)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(cowplot)
theme_set(theme_cowplot())
library(corrplot)
library(visreg)
library(ggcorrplot)
library(ggseg3d)
library(ggseg)
library(ggsegSchaefer)
library(ggsegYeo2011)
library(psych)
library(nlme)
library(mgcv)
library(gratia)

load(file="../../Dataset/childhood/atlas/schaefer17_400_3d.RData")
lh_label <- schaefer17_400_3d$ggseg_3d[[1]]['region'][2:201,1:1]
rh_label <- schaefer17_400_3d$ggseg_3d[[2]]['region'][2:201,1:1]
label <- rbind(lh_label, rh_label)
age_H <- read.csv("../../Derivatives/childhood/part_motion_0.5mm.csv")   
age_H_sorted <- read.csv("../../Derivatives/childhood/part_sorted_motion_0.5mm.csv")
concat <- read.csv('../../Derivatives/childhood/original_motion_0.5mm.csv')
age_H <- age_H[age_H$sub!='CBPD0015',]
age_H <- age_H[age_H$sub!='CBPD0247',]
age_H_sorted <- age_H_sorted[age_H_sorted$sub!='CBPD0015',]
age_H_sorted <- age_H_sorted[age_H_sorted$sub!='CBPD0247',]
k=3
```


```{r setup, include=FALSE}
# SupFig1E
n <- 267
colfunc <- colorRampPalette(c("yellow","purple"))(400)
col <- colnames(age_H_sorted)[(n):(133+n)]
allcol <- age_H_sorted[col[1]]
colnames(allcol) <- 'age'
for (x in col){
  colconcat <- age_H_sorted[x]
  colnames(colconcat) <- 'age'
  allcol <- rbind(allcol, colconcat)}
allages <- age_H_sorted['age_scan']
for (x in col){
  allages <- rbind(allages, age_H_sorted['age_scan'])}
allsex <- age_H_sorted['male']
for (x in col){
  allsex <- rbind(allsex, age_H_sorted['male'])}
allmotion <- age_H_sorted['meanFD']
for (x in col){
  allmotion <- rbind(allmotion, age_H_sorted['meanFD'])}
allcol <- cbind(allcol, allages, allsex, allmotion)
model <- gam(allcol[['age']] ~ s(age_scan, k=k) + male + meanFD, data = allcol)
pred <- predict(model, se.fit=T)
derv <- derivatives(model, interval = "simultaneous", unconditional = F)
increasing.range <- derv[['age_scan']][derv[['.upper_ci']] > 0]
print(max(increasing.range))
allcol$prediction <- pred$fit
allcol$ymin <- pred$fit-1.96*pred$se.fit
allcol$ymax <- pred$fit+1.96*pred$se.fit
p <- ggplot(data = allcol, mapping = aes(x = age_scan, y = prediction)) +
geom_smooth(method="gam", formula= y~s(x, k=k), se=TRUE, alpha=1) + ylim(0.75,0.85)
ggsave('Fig5C_0.5mm_noregress_267.eps', plot=p, width=6, height=4, units='in', dpi=300)#, device="eps")
```

```{r setup, include=FALSE}
colfunc <- colorRampPalette(c("yellow","purple"))(400)
schaefer_H <- data.frame(age=1:3)
pvalue <- data.frame(age=1:3)
t <- 1
for (n in c(1,134,267)){
  col <- colnames(age_H_sorted)[(n):(133+n)]
  allcol <- age_H_sorted[col[1]]
  colnames(allcol) <- 'age'
  for (x in col){
    colconcat <- age_H_sorted[x]
    colnames(colconcat) <- 'age'
    allcol <- rbind(allcol, colconcat)}
  allages <- age_H_sorted['age_scan']
  for (x in col){
    allages <- rbind(allages, age_H_sorted['age_scan'])}
  allsex <- age_H_sorted['male']
  for (x in col){
    allsex <- rbind(allsex, age_H_sorted['male'])}
  allt1 <- age_H_sorted['meanFD']
  for (x in col){
    allt1 <- rbind(allt1, age_H_sorted['meanFD'])}
  allcol <- cbind(allcol, allages, allsex, allt1)
  model <- gam(allcol[['age']] ~ s(age_scan, k=k) + male + meanFD, data = allcol)
  gam.model <- gam(allcol[['age']] ~ s(age_scan, k=k) + male + meanFD, data = allcol)
  gam.nullmodel <- gam(allcol[['age']] ~ male + meanFD, data = allcol)
  ### effect size
  sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
  sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
  partialRsq <- (sse.nullmodel - sse.model)/sse.nullmodel
  mean.derivative <- mean(derv[['.derivative']])
  if(mean.derivative < 0){ #if the average derivative is less than 0, make the effect size estimate negative
    partialRsq <- partialRsq*-1}
  schaefer_H$age[t] <- partialRsq
  derv <- derivatives(gam.model, interval = "simultaneous", unconditional = F)
  pvalue$age[t] <- anova.gam(gam.nullmodel, gam.model, test='Chisq')$`Pr(>Chi)`[2]
  t <- t+1
}
```

```{r setup, include=FALSE}
correctedpvalue <- data.frame(age=1:3)
correctedpvalue$age <- p.adjust(pvalue$age, method=c("fdr"))
pvalue$age <- pvalue$age < 0.05
```