```{r setup, error=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(clue)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())
library(corrplot)
library(visreg)
library(ggcorrplot)
library(ggseg3d)
library(ggsegSchaefer)
library(ggsegYeo2011)
library(psych)
library(nlme)
library(mgcv)

concat <- read.csv('../../Derivatives/adult/original.csv')
indv <- read.csv('../../Derivatives/childhood/indv.csv')
```

```{r setup, error=TRUE, include=FALSE}
color.bar <- function(lut, min, max=-min, nticks=11, ticks=seq(min, max, len=nticks), title='') {
  scale = (length(lut)-1)/(max-min)
    dev.new(width=1.75, height=5)
    postscript('Fig5Gcolorbar.eps') 
    plot(c(0,10), c(min,max), type='n', bty='n', xaxt='n', xlab='', yaxt='n', ylab='', main=title)
    axis(2, ticks, las=1)
    for (i in 1:(length(lut)-1)) {
     y = (i-1)/scale + min
     rect(0,y,10,y+1/scale, col=lut[i], border=NA)
    }
    dev.off()  
}
color.bar(colorRampPalette(c("skyblue","darkblue"))(137), -1)
```

```{r setup, error=TRUE, include=FALSE}
# Figure6G
colfunc <- colorRampPalette(c("skyblue","darkblue"))(137)
postscript('Fig5G.eps') 
plot(indv[['H']],indv[['part']], ylim=c(0.7,0.9),
   xlab="Hurst Exponent", ylab="Participation Coefficient", pch=19, col=colfunc)
lmresult <- lm(indv[['part']]~indv[['H']])
preds <- predict(lmresult, newdata=data.frame(indv[['H']]), interval="confidence", level = 0.95)
abline(lmresult, col="black")
polygon(c(rev(indv[['H']][order(indv[['H']])]), indv[['H']][order(indv[['H']])]), c(rev(preds[ ,3][order(indv[['H']])]), preds[ ,2][order(indv[['H']])]), col = 'grey80', border = NA)
print(summary(lmresult))
dev.off()
```

```{r setup, error=TRUE, include=FALSE}
# Figure6H
colfunc <- colorRampPalette(c("yellow","purple"))(400)
postscript('Fig5H.eps') 
plot(concat[['H']],concat[['part']], 
   xlab="Hurst Exponent ", ylab="Participation Coefficient", pch=19, col=colfunc[concat[['SArank']]])
lmresult <- lm(concat[['part']]~concat[['H']])
preds <- predict(lmresult, newdata=data.frame(concat[['H']]), interval="confidence", level = 0.95)
abline(lmresult, col="black")
polygon(c(rev(concat[['H']][order(concat[['H']])]), concat[['H']][order(concat[['H']])]), c(rev(preds[ ,3][order(concat[['H']])]), preds[ ,2][order(concat[['H']])]), col = 'grey80', border = NA)
dev.off()
```