```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("WinVector/WVPlots")
library(WVPlots)
library(clue)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(cowplot)
theme_set(theme_cowplot())
library(corrplot)
library(visreg)
library(ggcorrplot)
library(ggseg3d)
library(ggseg)
library(ggsegSchaefer)
library(ggsegYeo2011)
library(psych)
library(nlme)
library(mgcv)
library(gratia)

load(file="../../Modules/human/schaefer17_400_3d.RData")
lh_label <- schaefer17_400_3d$ggseg_3d[[1]]['region'][2:201,1:1]
rh_label <- schaefer17_400_3d$ggseg_3d[[2]]['region'][2:201,1:1]
label <- rbind(lh_label, rh_label)
age_H <- read.csv("../../Derivatives/childhood/part.csv")   
age_H_sorted <- read.csv("../../Derivatives/childhood/part_sorted.csv")
concat <- read.csv('../../Derivatives/childhood/original.csv')

k=3
```

```{r setup, include=FALSE}
schaefer_H <- data.frame(age=1:400)
pvalue <- data.frame(age=1:400)
for (n in 1:400){
  col <- colnames(age_H)[n]
  gam.model <- gam(age_H[[col]] ~ s(age_scan, k=k) + male + t1_rating_avg, data = age_H)
  gam.nullmodel <- gam(age_H[[col]] ~ male + t1_rating_avg, data = age_H)
  derv <- derivatives(gam.model, interval = "simultaneous", unconditional = F)
  pvalue$age[n] <- anova.gam(gam.nullmodel, gam.model, test='Chisq')$`Pr(>Chi)`[2]
  ### effect size
  sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
  sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
  partialRsq <- (sse.nullmodel - sse.model)/sse.nullmodel
  ### effect direction
  mean.derivative <- mean(derv$derivative)
  if(mean.derivative < 0){ #if the average derivative is less than 0, make the effect size estimate negative
    partialRsq <- partialRsq*-1}
  schaefer_H$age[n] <- partialRsq
}
```

```{r setup, include=FALSE}
correctedpvalue <- data.frame(age=1:400)
correctedpvalue$age <- p.adjust(pvalue$age, method=c("fdr")) < 0.05
pvalue$age <- pvalue$age < 0.05
schaefer_H_extractp <- schaefer_H
schaefer_H_extractp[pvalue==FALSE] <- NA
schaefer_H_extractp <- cbind(schaefer_H_extractp, label)
schaefer_H_extractpadj <- schaefer_H
schaefer_H_extractpadj[correctedpvalue==FALSE] <- NA
schaefer_H_extractpadj <- cbind(schaefer_H_extractpadj, label)
write_csv(schaefer_H_extractp, '../../Derivatives/childhood/H_gam_ageeffect.csv')
```

```{r setup, include=FALSE}
# Figure5C
k = 3
colfunc <- colorRampPalette(c("yellow","purple"))(400)
postscript('Fig5C.eps') 
for (n in 1:400){
  col <- colnames(age_H_sorted)[n]
  model <- gam(age_H_sorted[[col]] ~ s(age_scan, k=k) + male + t1_rating_avg, data = age_H_sorted)
  if (n==400){
    plot(model, se=FALSE, residuals=FALSE, shade=FALSE, col=colfunc[n], ylab='Participation Coefficient (z-scored)', ylim=c(-1.5,1.5), xlim=c(4,11), xlab='Age')} #ylim=c(-1,1), 
  else {
    plot(model, se=FALSE, residuals=FALSE, shade=FALSE, col=colfunc[n], ylab='',yaxt="n" ,ylim=c(-1.5,1.5),   xlim=c(4,11),xlab='',xaxt="n" )
  par(new=T)} #
}
dev.off()
```

```{r setup, include=FALSE}
# Figure5D
colfunc <- colorRampPalette(c("yellow","purple"))(400)
postscript('Fig5D.eps')
for (n in c(1,134,267)){
  col <- colnames(age_H_sorted)[(n):(133+n)]
  allcol <- age_H_sorted[col[1]]
  colnames(allcol) <- 'age'
  for (x in col){
    colconcat <- age_H_sorted[x]
    colnames(colconcat) <- 'age'
    allcol <- rbind(allcol, colconcat)}
  allages <- age_H_sorted['age_scan']
  for (x in col){
    allages <- rbind(allages, age_H_sorted['age_scan'])}
  allsex <- age_H_sorted['male']
  for (x in col){
    allsex <- rbind(allsex, age_H_sorted['male'])}
  allt1 <- age_H_sorted['t1_rating_avg']
  for (x in col){
    allt1 <- rbind(allt1, age_H_sorted['t1_rating_avg'])}
  allcol <- cbind(allcol, allages, allsex, allt1)
  model <- gam(allcol[['age']] ~ s(age_scan, k=k) + male + t1_rating_avg, data = allcol)
  plot(model, se=TRUE, residuals=FALSE, shade=TRUE, shade.col=colfunc[n], shade.alpha=0.1, col=colfunc[n], xlim=c(4,11),ylab='Participation Coefficient (z-scored)', xlab='Age') #  ylim=c(-1,6),
  par(new=T)
}
dev.off()
```

```{r setup, include=FALSE}
# Figure5E
ggseg(schaefer_H_extractpadj, atlas = schaefer17_400, mapping = aes(fill = age),
      position = "stacked") +
  scale_fill_gradientn(colours=c("blue", 'white', "red"), name = bquote(age_effect), values = scales::rescale(c(-0.5, -0.05, 0, 0.05, 0.5)), limit=c(-0.3, 0.3)) + theme_brain(text.size=16)
ggsave(filename ='Fig5E.eps', device = "pdf", dpi = 500) #, width = .5 , height = .5
```

```{r setup, include=FALSE}
schaefer_H[['SArank']] <- concat[['SArank']]
model <- gam(schaefer_H[['age']] ~ s(SArank, k=k), data = schaefer_H)
pred <- predict(model, se.fit=T)
ggplot(data = schaefer_H, mapping = aes(x = SArank, y = age)) +
  geom_point(aes(color = schaefer_H[['SArank']]))  +
  geom_ribbon(aes(ymin=pred$fit-1.96*pred$se.fit,
                   ymax=pred$fit+1.96*pred$se.fit), alpha = 1, fill = 'gray') +
  geom_smooth(method="gam", formula= y~s(x, k=k)) + scale_color_gradient(low='yellow', high='purple') +
  geom_line(size=.3, alpha = .8)
ggsave(file='Figure5F.eps', width=8, height=4, dpi=300)
print(summary(model))
```